# SA for the web app pod — will have cross-namespace secret access (misconfiguration)
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-web
  namespace: app

---
# SA for the database pod
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-db
  namespace: data
